version: '3.5'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test-php
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: test-php
  php:
    build: ./etc/docker/php
    volumes:
      - ./:/var/projects/test-php
  web:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./:/var/projects/test-php
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
